package chapter_16;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/*
 * Herbert Schildt
 * Java: A Beginners Guide
 * Page 588
 * Demonstration of the use of flags
 */

public class CBDemo implements ItemListener {

	JLabel jlabSelected;
	JLabel jlabChanged;
	JCheckBox jcbAlpha;
	JCheckBox jcbBeta;
	JCheckBox jcbGamma;

	public CBDemo() {
		// Create new container JFrame
		JFrame jfrm = new JFrame("Demonstrate Check Boxes");

		// Set the FlowLayout object for the layout manager
		jfrm.setLayout(new FlowLayout());

		// Set initial size frame
		jfrm.setSize(280, 120);

		// Shut down program when the user closes the application
		jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		// Create empty label
		jlabSelected = new JLabel("");
		jlabChanged = new JLabel("");

		// Create flags
		jcbAlpha = new JCheckBox("Alpha");
		jcbBeta = new JCheckBox("Beta");
		jcbGamma = new JCheckBox("Gamma");

		// Events generated by flags are processed by one method itemStateChanged,
		// implemented in CBDemo class
		jcbAlpha.addItemListener(this);
		jcbBeta.addItemListener(this);
		jcbGamma.addItemListener(this);

		// Add flags and label in the content pane
		jfrm.add(jcbAlpha);
		jfrm.add(jcbBeta);
		jfrm.add(jcbGamma);
		jfrm.add(jlabChanged);
		jfrm.add(jlabSelected);

		// Display frame
		jfrm.setVisible(true);

	}

	// Flag handler
	@Override
	public void itemStateChanged(ItemEvent e) {
		// Handling flag events
		String str = "";

		// Get a link to the check box associated with the event
		JCheckBox cb = (JCheckBox) e.getItem();

		// Report the status of the checkbox
		if (cb.isSelected())
			jlabChanged.setText(cb.getText() + " was just selected.");
		else
			jlabChanged.setText(cb.getText() + " was just cleared.");

		// Report all checked boxes
		if (jcbAlpha.isSelected()) {
			str += "Alpha ";
		}
		if (jcbBeta.isSelected()) {
			str += "Beta ";
		}
		if (jcbGamma.isSelected()) {
			str += "Gamma";
		}

		jlabSelected.setText("Selected check boxes: " + str);

	}

	public static void main(String[] args) {
		// Create a frame in the event dispatching flows
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				new CBDemo();
			}
		});
	}
}